# Default tasks for role kvm-host

- name: Importing specific distro variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - always
  
- block:
    - name: Dropping Virt SIG kvm power repo if needed
      template:
        src: centos-kvm-power.repo
        dest: /etc/yum.repos.d/centos-kvm-power.repo
    - name: Adding Virt SIG GPG key
      copy:
        src: RPM-GPG-KEY-CentOS-SIG-Virtualization
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Virtualization
  when:
    - ansible_distribution_major_version|int > 9
    - ansible_architecture=='ppc64le'
  tags:
    - repo

- name: Ensuring KVM qemu tools are installed
  yum: 
    name: "{{ kvm_pkgs }}"
    state: installed

- name: Ensuring libvirtd is started
  service: 
    name: libvirtd 
    state: started 
    enabled: yes

- name: Defining a directory to hold all kickstart files
  file: 
    path: /var/lib/libvirt/local-kickstarts/ 
    state: directory 
    owner: root 
    group: root

- include_tasks: storage.yml
  when: kvm_host_manage_storage

- name: Ensuring correct selinux context
  file:
    path: /var/lib/libvirt/images
    state: directory
    setype: virt_image_t

- include_tasks: network.yml
  tags: 
    - network
