- name: Ensuring KVM qemu tools are installed
  yum: 
    name: ['qemu-kvm-tools', 'qemu-kvm', 'virt-install', 'libvirt', 'libvirt-python', 'libguestfs-tools-c']
    state: installed

- name: Ensuring libvirtd is started
  service: 
    name: libvirtd 
    state: started 
    enabled: yes

- name: Defining a directory to hold all kickstart files
  file: 
    path: /var/lib/libvirt/local-kickstarts/ 
    state: directory 
    owner: root 
    group: root

- include_tasks: storage.yml
  when: kvm_host_manage_storage

- name: Ensuring correct selinux context
  file:
    path: /var/lib/libvirt/images
    state: directory
    setype: virt_image_t

- include_tasks: network.yml
  tags: 
    - network
